**1.24.** Show that ρ is pure if and only if tr(ρ²) = 1.


In [13]:
import numpy as np
print("Problem 1.24:")
# Problem 1.24
def is_pure_state(rho):
    """Check if a density matrix represents a pure state"""
    trace_rho_squared = np.trace(np.matmul(rho, rho))
    return np.isclose(trace_rho_squared, 1.0)

# Test pure and mixed states
pure_state = np.array([[1, 0], [0, 0]])
mixed_state = np.array([[0.5, 0], [0, 0.5]])
print("Pure state:")
print(pure_state)
print("Mixed state:")
print(mixed_state)
print("Pure state is pure:", is_pure_state(pure_state))
print("Mixed state is pure:", is_pure_state(mixed_state))

Problem 1.24:
Pure state:
[[1 0]
 [0 0]]
Mixed state:
[[0.5 0. ]
 [0.  0.5]]
Pure state is pure: True
Mixed state is pure: False


**1.25**
Verify that ρ1 is a density matrix, where:
ρ1 = [[(1+p)/4, 0,    0,    p/2 ],
[0,    (1-p)/4, 0,    0   ],
[0,    0,    (1-p)/4, 0   ],
[p/2,  0,    0,    (1+p)/4]]
(0 ≤ p ≤ 1)

In [14]:
# Problem 1.25
def is_density_matrix(rho):
    """Check if a matrix is a valid density matrix"""
    # Check Hermiticity
    if not np.allclose(rho, rho.conj().T):
        return False


    # Check trace = 1
    if not np.isclose(np.trace(rho), 1.0):
        return False

    # Check positive semidefiniteness
    eigenvalues = np.linalg.eigvals(rho)
    if np.any(eigenvalues < -1e-10):  # Allow for small numerical errors
        return False

    return True

def create_rho1(p):
    """Create the density matrix ρ1 for a given p"""
    return np.array([
        [(1+p)/4, 0, 0, p/2],
        [0, (1-p)/4, 0, 0],
        [0, 0, (1-p)/4, 0],
        [p/2, 0, 0, (1+p)/4]
    ])

# Test for different values of p
p_values = [0, 0.3 , 0.6, 1]

print("\nProblem 1.25:")
for p in p_values:
    rho1 = create_rho1(p)
    print(f"For p = {p}:")
    print("Is a valid density matrix:", is_density_matrix(rho1))
    print("Eigenvalues:", np.linalg.eigvals(rho1))
    print()


Problem 1.25:
For p = 0:
Is a valid density matrix: True
Eigenvalues: [0.25 0.25 0.25 0.25]

For p = 0.3:
Is a valid density matrix: True
Eigenvalues: [0.475 0.175 0.175 0.175]

For p = 0.6:
Is a valid density matrix: True
Eigenvalues: [0.7 0.1 0.1 0.1]

For p = 1:
Is a valid density matrix: True
Eigenvalues: [1.00000000e+00 1.11022302e-16 0.00000000e+00 0.00000000e+00]



**1.27**: Density Matrix and Partial Trace of an Entangled State
Let |Ψ'⟩ = 1/√2 (|e₁⟩|e₂⟩ - |e₂⟩|e₁⟩).
a) Find the corresponding density matrix.

In [15]:
# Define the basis states
e1 = np.array([1, 0])
e2 = np.array([0, 1.00000001])

# Define the state |Ψ'⟩ = 1/√2 (|e₁⟩|e₂⟩ - |e₂⟩|e₁⟩)
psi_prime = 1/np.sqrt(2) * (np.kron(e1, e2) - np.kron(e2, e1))

# Calculate the density matrix ρ = |Ψ'⟩⟨Ψ'|
rho = np.outer(psi_prime, psi_prime.conj())

print("The state |Ψ'⟩:")
print(psi_prime)

print("\nThe corresponding density matrix ρ:")
print(rho)
# Verify properties of the density matrix
print("\nTrace of the density matrix:", np.trace(rho).real)
print("Is the matrix Hermitian?", np.allclose(rho, rho.conj().T))
print("Eigenvalues of the density matrix:", np.linalg.eigvals(rho))
print("Is a valid density matrix:", is_density_matrix(rho))


The state |Ψ'⟩:
[ 0.          0.70710679 -0.70710679  0.        ]

The corresponding density matrix ρ:
[[ 0.          0.         -0.          0.        ]
 [ 0.          0.50000001 -0.50000001  0.        ]
 [-0.         -0.50000001  0.50000001 -0.        ]
 [ 0.          0.         -0.          0.        ]]

Trace of the density matrix: 1.0000000199999997
Is the matrix Hermitian? True
Eigenvalues of the density matrix: [1.00000002 0.         0.         0.        ]
Is a valid density matrix: True



Partial-trace it over the first Hilbert space to find a
density matrix of the second system.


In [16]:


print("The original density matrix ρ:")
print(rho)

# Function to perform partial trace
def partial_trace(rho, keep, dim):
    """
    Compute the partial trace of a density matrix.

    :param rho: The density matrix
    :param keep: The index of the subsystem to keep (0 for first, 1 for second)
    :param dim: The dimension of each subsystem
    :return: The reduced density matrix
    """
    reshaped_rho = rho.reshape([dim, dim, dim, dim])
    if keep == 0:
        return np.trace(reshaped_rho, axis1=1, axis2=3)
    elif keep == 1:
        return np.trace(reshaped_rho, axis1=0, axis2=2)
    else:
        raise ValueError("'keep' should be 0 or 1")

# Perform partial trace over the first system
rho_B = partial_trace(rho, keep=0, dim=2)

print("\nReduced density matrix of the second system:")
print(rho_B)

# Verify properties of the reduced density matrix
print("\nTrace of the reduced density matrix:", np.trace(rho_B).real)
print("Is the reduced density matrix Hermitian?", np.allclose(rho_B, rho_B.conj().T))
print("Eigenvalues of the reduced density matrix:", np.linalg.eigvals(rho_B))

The original density matrix ρ:
[[ 0.          0.         -0.          0.        ]
 [ 0.          0.50000001 -0.50000001  0.        ]
 [-0.         -0.50000001  0.50000001 -0.        ]
 [ 0.          0.         -0.          0.        ]]

Reduced density matrix of the second system:
[[0.50000001 0.        ]
 [0.         0.50000001]]

Trace of the reduced density matrix: 1.0000000199999997
Is the reduced density matrix Hermitian? True
Eigenvalues of the reduced density matrix: [0.50000001 0.50000001]


**1.28:**  Density Matrix Purification
Let ρ₁ = 1/4 [1 0; 0 3] be a density matrix with a basis {|Ψᵢ⟩}. Find a purification of ρ₁.

In [17]:
import numpy as np

# Define the density matrix ρ₁
rho_1 = np.array([[1/4, 0],
                  [0, 3/4]])

print("Original density matrix ρ₁:")
print(rho_1)

# Find the eigenvalues and eigenvectors of ρ₁
eigenvalues, eigenvectors = np.linalg.eigh(rho_1)

print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

# Construct the purification |Ψ⟩
psi = np.zeros((4, 1), dtype=complex)
for i in range(2):
    psi[2*i:2*i+2, 0] = np.sqrt(eigenvalues[i]) * eigenvectors[:, i]

print("\nPurification |Ψ⟩:")
print(psi)

# Verify the purification by reconstructing ρ₁
rho_reconstructed = np.trace(np.outer(psi, psi.conj()).reshape(2, 2, 2, 2), axis1=1, axis2=3)

print("\nReconstructed ρ₁ from purification:")
print(rho_reconstructed)

# Check if the reconstructed matrix matches the original
print("\nDoes the purification reproduce ρ₁?")
print(np.allclose(rho_1, rho_reconstructed))

Original density matrix ρ₁:
[[0.25 0.  ]
 [0.   0.75]]

Eigenvalues:
[0.25 0.75]

Eigenvectors:
[[1. 0.]
 [0. 1.]]

Purification |Ψ⟩:
[[0.5      +0.j]
 [0.       +0.j]
 [0.       +0.j]
 [0.8660254+0.j]]

Reconstructed ρ₁ from purification:
[[0.25+0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j]]

Does the purification reproduce ρ₁?
True


**1.31:** Fidelity Calculation between Two Density Matrices
Let ρ1 = 1/2 [1 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 1]
and ρ2 = 1/2 [1 0 0 1; 0 0 0 0; 0 0 0 0; 1 0 0 1].
Find the fidelity F(ρ1, ρ2).

In [18]:


# Define the density matrices
rho1 = 1/2 * np.array([[1, 0, 0, 0],
                       [0, 0, 0, 0],
                       [0, 0, 0, 0],
                       [0, 0, 0, 1]])

rho2 = 1/2 * np.array([[1, 0, 0, 1],
                       [0, 0, 0, 0],
                       [0, 0, 0, 0],
                       [1, 0, 0, 1]])

print("Density matrix ρ1:")
print(rho1)
print("\nDensity matrix ρ2:")
print(rho2)

# Debugged and corrected fidelity calculation
def fidelity(rho1, rho2):
    # Ensure the matrices are Hermitian
    rho1 = (rho1 + rho1.conj().T) / 2
    rho2 = (rho2 + rho2.conj().T) / 2

    # Calculate the square root of rho1
    eigvals, eigvecs = np.linalg.eigh(rho1)
    sqrt_rho1 = np.dot(eigvecs * np.sqrt(eigvals), eigvecs.conj().T)

    # Calculate the product
    product = np.dot(sqrt_rho1, np.dot(rho2, sqrt_rho1))

    # Calculate the trace of the square root of the product
    return np.real(np.trace(np.sqrt(product)))

F = fidelity(rho1, rho2)

print(f"\nThe fidelity F(ρ1, ρ2) = {F}")

# Verify properties of fidelity
print(f"\nF(ρ1, ρ1) = {fidelity(rho1, rho1)}")  # Should be 1
print(f"F(ρ2, ρ2) = {fidelity(rho2, rho2)}")  # Should be 1
print(f"F(ρ2, ρ1) = {fidelity(rho2, rho1)}")  # Should be equal to F(ρ1, ρ2)

# Calculate analytical result
analytical_result = np.sqrt(3/4)
print(f"\nAnalytical result = {analytical_result}")
print(f"Difference from numerical result: {abs(F - analytical_result)}")

Density matrix ρ1:
[[0.5 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]

Density matrix ρ2:
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

The fidelity F(ρ1, ρ2) = 1.0

F(ρ1, ρ1) = 1.0
F(ρ2, ρ2) = 1.4142135623730947
F(ρ2, ρ1) = 0.9999999999999998

Analytical result = 0.8660254037844386
Difference from numerical result: 0.1339745962155614


**2.2:** Density Matrix and Bloch Representation
Find the density matrix of |Ψ(θ, φ)⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩ and write it in the form ρ = 1/2(I + Σ uiσi).

In [19]:

def density_matrix(theta, phi):
    # Define the state |Ψ(θ, φ)⟩
    psi = np.array([np.cos(theta/2), np.exp(1j*phi) * np.sin(theta/2)])

    # Calculate the density matrix ρ = |Ψ⟩⟨Ψ|
    rho = np.outer(psi, np.conj(psi))

    return rho

def density_matrix_bloch(theta, phi):
    # Calculate the Bloch sphere coordinates
    u1 = np.sin(theta) * np.cos(phi)
    u2 = np.sin(theta) * np.sin(phi)
    u3 = np.cos(theta)

    # Pauli matrices
    sigma1 = np.array([[0, 1], [1, 0]])
    sigma2 = np.array([[0, -1j], [1j, 0]])
    sigma3 = np.array([[1, 0], [0, -1]])

    # Calculate ρ = 1/2(I + Σ uiσi)
    I = np.eye(2)
    rho = 0.5 * (I + u1*sigma1 + u2*sigma2 + u3*sigma3)

    return rho, [u1, u2, u3]

# Example calculation
theta = np.pi/4  # You can change these values
phi = np.pi/3

rho = density_matrix(theta, phi)
rho_bloch, u = density_matrix_bloch(theta, phi)

print("Density matrix ρ:")
print(rho)
print("\nDensity matrix in Bloch representation:")
print(rho_bloch)
print("\nBloch vector components (u1, u2, u3):")
print(u)

# Verify that both methods give the same result
print("\nAre the results equal?")
print(np.allclose(rho, rho_bloch))

Density matrix ρ:
[[0.85355339+0.00000000e+00j 0.1767767 -3.06186218e-01j]
 [0.1767767 +3.06186218e-01j 0.14644661+6.91860793e-18j]]

Density matrix in Bloch representation:
[[0.85355339+0.j         0.1767767 -0.30618622j]
 [0.1767767 +0.30618622j 0.14644661+0.j        ]]

Bloch vector components (u1, u2, u3):
[0.3535533905932738, 0.6123724356957945, 0.7071067811865476]

Are the results equal?
True


 **2.3:** Expectation Value of Pauli Matrices
Let ρ be given by ρ = 1/2(I + Σ uiσi). Show that ⟨σ⟩ = tr(ρσ) = u = (u1, u2, u3), where σ = (σx, σy, σz).

In [20]:


# Define Pauli matrices
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])
sigma = [sigma_x, sigma_y, sigma_z]

# Define identity matrix
I = np.eye(2)

def rho(u):
    """Construct density matrix from Bloch vector u"""
    return 0.5 * (I + u[0]*sigma_x + u[1]*sigma_y + u[2]*sigma_z)

def expectation_value(rho, operator):
    """Calculate tr(ρσ)"""
    return np.trace(np.matmul(rho, operator))

# Test for a random Bloch vector
u = np.random.rand(3)
u = u / np.linalg.norm(u)  # Normalize to ensure it's a valid Bloch vector

print("Bloch vector u:", u)

# Calculate density matrix
density_matrix = rho(u)

# Calculate ⟨σ⟩ = tr(ρσ) for each Pauli matrix
expectation_values = [expectation_value(density_matrix, s) for s in sigma]

print("\nExpectation values ⟨σ⟩:")
print(expectation_values)

# Check if ⟨σ⟩ = u
print("\nAre ⟨σ⟩ and u equal?")
print(np.allclose(expectation_values, u, atol=1e-8))




Bloch vector u: [0.04705336 0.74031215 0.67061457]

Expectation values ⟨σ⟩:
[(0.047053361855663056+0j), (0.7403121535021471+0j), (0.6706145662860994+0j)]

Are ⟨σ⟩ and u equal?
True



**2.4** The Bell basis is obtained from the binary basis {|00⟩, |01⟩, |10⟩, |11⟩} by a unitary transformation. Write it down explicitly




In [21]:

# Define the binary basis states
state_00 = np.array([1, 0, 0, 0])
state_01 = np.array([0, 1, 0, 0])
state_10 = np.array([0, 0, 1, 0])
state_11 = np.array([0, 0, 0, 1])

# Define the Bell states
phi_plus = 1/np.sqrt(2) * (state_00 + state_11)
phi_minus = 1/np.sqrt(2) * (state_00 - state_11)
psi_plus = 1/np.sqrt(2) * (state_01 + state_10)
psi_minus = 1/np.sqrt(2) * (state_01 - state_10)

# Create a matrix with Bell states as rows
bell_basis = np.vstack([phi_plus, phi_minus, psi_plus, psi_minus])

print("Bell basis states:")
print("\n|Φ⁺⟩ = ", phi_plus)
print("\n|Φ⁻⟩ = ", phi_minus)
print("\n|Ψ⁺⟩ = ", psi_plus)
print("\n|Ψ⁻⟩ = ", psi_minus)

# Verify orthonormality
print("\nVerifying orthonormality:")
for i, state1 in enumerate([phi_plus, phi_minus, psi_plus, psi_minus]):
    for j, state2 in enumerate([phi_plus, phi_minus, psi_plus, psi_minus]):
        inner_product = np.abs(np.dot(state1.conj(), state2))
        print(f"⟨Bell{i+1}|Bell{j+1}⟩ = {inner_product:.1f}")

# Verify that the transformation is unitary
is_unitary = np.allclose(np.dot(bell_basis, bell_basis.conj().T), np.eye(4))
print("\nIs the transformation unitary?", is_unitary)

Bell basis states:

|Φ⁺⟩ =  [0.70710678 0.         0.         0.70710678]

|Φ⁻⟩ =  [ 0.70710678  0.          0.         -0.70710678]

|Ψ⁺⟩ =  [0.         0.70710678 0.70710678 0.        ]

|Ψ⁻⟩ =  [ 0.          0.70710678 -0.70710678  0.        ]

Verifying orthonormality:
⟨Bell1|Bell1⟩ = 1.0
⟨Bell1|Bell2⟩ = 0.0
⟨Bell1|Bell3⟩ = 0.0
⟨Bell1|Bell4⟩ = 0.0
⟨Bell2|Bell1⟩ = 0.0
⟨Bell2|Bell2⟩ = 1.0
⟨Bell2|Bell3⟩ = 0.0
⟨Bell2|Bell4⟩ = 0.0
⟨Bell3|Bell1⟩ = 0.0
⟨Bell3|Bell2⟩ = 0.0
⟨Bell3|Bell3⟩ = 1.0
⟨Bell3|Bell4⟩ = 0.0
⟨Bell4|Bell1⟩ = 0.0
⟨Bell4|Bell2⟩ = 0.0
⟨Bell4|Bell3⟩ = 0.0
⟨Bell4|Bell4⟩ = 1.0

Is the transformation unitary? True


**2.5** Find the expectation value of X ⊗ Z measured in each of the Bell states.



In [22]:

# Define Pauli matrices
X = np.array([[0, 1], [1, 0]])
Z = np.array([[1, 0], [0, -1]])
I = np.eye(2)

# Define X⊗Z operator using Kronecker product
XZ = np.kron(X, Z)

# Define Bell states
def bell_states():
    """Return the four Bell states"""
    # |Φ⁺⟩ = 1/√2 (|00⟩ + |11⟩)
    phi_plus = 1/np.sqrt(2) * np.array([1, 0, 0, 1])

    # |Φ⁻⟩ = 1/√2 (|00⟩ - |11⟩)
    phi_minus = 1/np.sqrt(2) * np.array([1, 0, 0, -1])

    # |Ψ⁺⟩ = 1/√2 (|01⟩ + |10⟩)
    psi_plus = 1/np.sqrt(2) * np.array([0, 1, 1, 0])

    # |Ψ⁻⟩ = 1/√2 (|01⟩ - |10⟩)
    psi_minus = 1/np.sqrt(2) * np.array([0, 1, -1, 0])

    return [phi_plus, phi_minus, psi_plus, psi_minus]

def expectation_value(state, operator):
    """Calculate expectation value ⟨ψ|O|ψ⟩"""
    return np.real(np.dot(state.conj(), np.dot(operator, state)))

# Calculate expectation values
states = bell_states()
state_names = ['|Φ⁺⟩', '|Φ⁻⟩', '|Ψ⁺⟩', '|Ψ⁻⟩']

print("X⊗Z operator:")
print(XZ)
print("\nExpectation values of X⊗Z:")

for state, name in zip(states, state_names):
    value = expectation_value(state, XZ)
    print(f"⟨{name}|X⊗Z|{name}⟩ = {value}")

# Verify that states are eigenstates by checking if X⊗Z|ψ⟩ = ±|ψ⟩
print("\nVerifying if states are eigenstates:")
for state, name in zip(states, state_names):
    operated_state = np.dot(XZ, state)
    ratio = operated_state/state
    ratio = ratio[np.nonzero(state)[0][0]]  # Get first non-zero element
    print(f"{name} is eigenstate with eigenvalue {ratio}")

X⊗Z operator:
[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]

Expectation values of X⊗Z:
⟨|Φ⁺⟩|X⊗Z||Φ⁺⟩⟩ = 0.0
⟨|Φ⁻⟩|X⊗Z||Φ⁻⟩⟩ = 0.0
⟨|Ψ⁺⟩|X⊗Z||Ψ⁺⟩⟩ = 0.0
⟨|Ψ⁻⟩|X⊗Z||Ψ⁻⟩⟩ = 0.0

Verifying if states are eigenstates:
|Φ⁺⟩ is eigenstate with eigenvalue 0.0
|Φ⁻⟩ is eigenstate with eigenvalue 0.0
|Ψ⁺⟩ is eigenstate with eigenvalue 0.0
|Ψ⁻⟩ is eigenstate with eigenvalue 0.0


<ipython-input-22-b0504dc07fe2>:46: RuntimeWarning: divide by zero encountered in divide
  ratio = operated_state/state


In [23]:
import numpy as np

# Define Pauli matrices
X = np.array([[0, 1],
              [1, 0]])
Z = np.array([[1, 0],
              [0, -1]])

# Calculate X⊗Z using Kronecker product
XZ = np.kron(X, Z)

# Define Bell states in the computational basis {|00⟩, |01⟩, |10⟩, |11⟩}
def bell_states():
    """Return the four Bell states"""
    # |Φ⁺⟩ = 1/√2 (|00⟩ + |11⟩)
    phi_plus = 1/np.sqrt(2) * np.array([1, 0, 0, 1])

    # |Φ⁻⟩ = 1/√2 (|00⟩ - |11⟩)
    phi_minus = 1/np.sqrt(2) * np.array([1, 0, 0, -1])

    # |Ψ⁺⟩ = 1/√2 (|01⟩ + |10⟩)
    psi_plus = 1/np.sqrt(2) * np.array([0, 1, 1, 0])

    # |Ψ⁻⟩ = 1/√2 (|01⟩ - |10⟩)
    psi_minus = 1/np.sqrt(2) * np.array([0, 1, -1, 0])

    return [phi_plus, phi_minus, psi_plus, psi_minus]

# Display X⊗Z operator
print("X⊗Z operator:")
print(XZ)

# Calculate expectation values
states = bell_states()
state_names = ['|Φ⁺⟩', '|Φ⁻⟩', '|Ψ⁺⟩', '|Ψ⁻⟩']

print("\nExpectation values of X⊗Z:")

# Calculate each expectation value
for state, name in zip(states, state_names):
    # First apply X⊗Z to |ψ⟩
    XZ_state = np.dot(state.conj(), XZ)
    # Then calculate ⟨ψ|X⊗Z|ψ⟩
    expectation = np.dot(XZ_state,state)
    print(f"⟨{name}.conj()|X⊗Z|{name}⟩ = {expectation.real}")

# Verify that |Ψ±⟩ are eigenstates
print("\nVerifying eigenstate properties:")
for state, name in zip(states[2:], state_names[2:]):
    XZ_state = np.dot(XZ, state)
    print(f"\nX⊗Z|{name}⟩ =")
    print(XZ_state)
    print(f"Original {name} =")
    print(state)

X⊗Z operator:
[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]

Expectation values of X⊗Z:
⟨|Φ⁺⟩.conj()|X⊗Z||Φ⁺⟩⟩ = 0.0
⟨|Φ⁻⟩.conj()|X⊗Z||Φ⁻⟩⟩ = 0.0
⟨|Ψ⁺⟩.conj()|X⊗Z||Ψ⁺⟩⟩ = 0.0
⟨|Ψ⁻⟩.conj()|X⊗Z||Ψ⁻⟩⟩ = 0.0

Verifying eigenstate properties:

X⊗Z||Ψ⁺⟩⟩ =
[ 0.70710678  0.          0.         -0.70710678]
Original |Ψ⁺⟩ =
[0.         0.70710678 0.70710678 0.        ]

X⊗Z||Ψ⁻⟩⟩ =
[-0.70710678  0.          0.         -0.70710678]
Original |Ψ⁻⟩ =
[ 0.          0.70710678 -0.70710678  0.        ]


**2.6** (QKD) Model the transmission from a bit 0, encoded by Alice in the {| ↑⟩, | ↓⟩} basis, the
interception by Eve by measuring with the basis {| ↗⟩, | ↘⟩} and final reception by Bob,
who measures the incoming qubit with the basis {| ↑⟩, | ↓⟩}. What is the probability that Bob
obtains 0 as a result to his measurement?

In [24]:


def state_in_computational_basis(theta):
    """Create state |ψ⟩ = cos(θ)|0⟩ + sin(θ)|1⟩"""
    return np.array([np.cos(theta), np.sin(theta)])

# Step 1: Define the initial state (Alice's bit 0 in {|↑⟩, |↓⟩} basis)
# |↑⟩ corresponds to bit 0, equivalent to |0⟩ in computational basis
alice_state = np.array([1, 0])

# Step 2: Define Eve's measurement basis {|↗⟩, |↘⟩}
# |↗⟩ = 1/√2(|0⟩ + |1⟩)
# |↘⟩ = 1/√2(|0⟩ - |1⟩)
eve_basis_plus = 1/np.sqrt(2) * np.array([1, 1])
eve_basis_minus = 1/np.sqrt(2) * np.array([1, -1])

print("Initial state (Alice's |↑⟩):")
print(alice_state)

# Step 3: Calculate probabilities for Eve's measurement
prob_eve_plus = np.abs(np.dot(eve_basis_plus.conj(), alice_state))**2
prob_eve_minus = np.abs(np.dot(eve_basis_minus.conj(), alice_state))**2

print("\nProbabilities for Eve's measurement:")
print(f"P(|↗⟩) = {prob_eve_plus:.3f}")
print(f"P(|↘⟩) = {prob_eve_minus:.3f}")

# Step 4: Calculate post-measurement states after Eve's measurement
# If Eve measures |↗⟩, state becomes |↗⟩
# If Eve measures |↘⟩, state becomes |↘⟩

# Step 5: Calculate probability for Bob to measure 0 (|↑⟩) for each of Eve's outcomes
prob_bob_0_given_eve_plus = np.abs(np.dot(alice_state.conj(), eve_basis_plus))**2
prob_bob_0_given_eve_minus = np.abs(np.dot(alice_state.conj(), eve_basis_minus))**2

# Step 6: Calculate total probability using law of total probability
total_prob = (prob_eve_plus * prob_bob_0_given_eve_plus +
              prob_eve_minus * prob_bob_0_given_eve_minus)

print("\nProbabilities for Bob's measurement of |↑⟩ (0):")
print(f"P(0|Eve measured |↗⟩) = {prob_bob_0_given_eve_plus:.3f}")
print(f"P(0|Eve measured |↘⟩) = {prob_bob_0_given_eve_minus:.3f}")
print(f"\nTotal probability for Bob to measure 0: {total_prob:.3f}")




Initial state (Alice's |↑⟩):
[1 0]

Probabilities for Eve's measurement:
P(|↗⟩) = 0.500
P(|↘⟩) = 0.500

Probabilities for Bob's measurement of |↑⟩ (0):
P(0|Eve measured |↗⟩) = 0.500
P(0|Eve measured |↘⟩) = 0.500

Total probability for Bob to measure 0: 0.500
