# 1.1 Show that the following set of vectors is a basis of C³:

|v₁⟩ = (1, 1, 1)ᵗ
|v₂⟩ = (1, 0, 1)ᵗ
|v₃⟩ = (1, -1, -1)ᵗ




In [3]:
import numpy as np

# Define the vectors
v1 = np.array([1, 1, 1])
v2 = np.array([1, 0, 1])
v3 = np.array([1, -1, -1])

# Stack the vectors into a matrix
matrix = np.column_stack([v1, v2, v3])

# Calculate the determinant of the matrix
determinant = np.linalg.det(matrix)

# Check if the determinant is non-zero (which indicates the vectors are linearly independent)
determinant


2.0

## 1.2 Given the following vectors:

|x⟩ = (1, i, 2 + i)ᵗ
|y⟩ = (2 - i, 1, 2 + i)ᵗ

Find:
1. ‖|x⟩‖
2. ⟨x|y⟩
3. ⟨y|x⟩


In [4]:
# Define the vectors x and y
x = np.array([1, 1j, 2 + 1j])
y = np.array([2 - 1j, 1, 2 + 1j])

# Norm of x
norm_x = np.linalg.norm(x)

# Inner product ⟨x|y⟩
inner_product_xy = np.vdot(x, y)

# Inner product ⟨y|x⟩
inner_product_yx = np.vdot(y, x)

norm_x, inner_product_xy, inner_product_yx


(2.6457513110645907, (7-2j), (7+2j))

## 1.3 Prove that:

⟨x|y⟩ = ⟨y|x⟩*

Note: The asterisk (*) denotes complex conjugate.

In [5]:
# Verify that ⟨x|y⟩ = ⟨y|x⟩* in Python

# Check if the complex conjugate of ⟨y|x⟩ is equal to ⟨x|y⟩
verification = np.isclose(inner_product_xy, np.conj(inner_product_yx))

verification


True

## 1.4 Given the following vectors:

|e₁⟩ = (1/√2, 1/√2)ᵗ
|e₂⟩ = (1/√2, -1/√2)ᵗ

Let |v⟩ = (3, 2)ᵗ = ∑₂ₖ₌₁ cₖ|eₖ⟩

Find c₁ and c₂.

In [6]:
# Define the vectors e1, e2, and v
e1 = np.array([1, 1]) / np.sqrt(2)
e2 = np.array([1, -1]) / np.sqrt(2)
v = np.array([3, 2])

# Calculate the coefficients c1 and c2 using the inner product
c1 = np.dot(e1, v)
c2 = np.dot(e2, v)

print(c1, c2)
c1*e1 + c2*e2

3.5355339059327373 0.7071067811865475


array([3., 2.])

## 1.5 Gram-Schmidt Orthonormalization and Coefficient Calculation

1. Use the Gram-Schmidt orthonormalization process to find an orthonormal basis {|eᵢ⟩} from the following set of vectors:

   |v₁⟩ = (-1, 2, 2)ᵗ
   |v₂⟩ = (2, -1, 2)ᵗ
   |v₃⟩ = (3, 0, -3)ᵗ

2. Let |u⟩ = (1, -2, 7)ᵗ = ∑ₖ cₖ|eₖ⟩

   Find the coefficients cₖ.

In [7]:
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        w = v - np.sum([np.dot(v, b) * b for b in basis], axis=0)
        if not np.allclose(w, 0):
            basis.append(w / np.linalg.norm(w))
    return np.array(basis)

# Define the initial vectors
v1 = np.array([-1, 2, 2])
v2 = np.array([2, -1, 2])
v3 = np.array([3, 0, -3])

vectors = [v1, v2, v3]

# Apply Gram-Schmidt orthonormalization
orthonormal_basis = gram_schmidt(vectors)

print("Orthonormal Basis:")
for i, e in enumerate(orthonormal_basis, 1):
    print(f"|e{i}⟩ =", e)

# Define the vector u
u = np.array([1, -2, 7])

# Calculate coefficients
coefficients = np.dot(orthonormal_basis, u)

print("\nCoefficients:")
for i, c in enumerate(coefficients, 1):
    print(f"c{i} =", c)

# Verify the result
reconstructed_u = np.dot(coefficients, orthonormal_basis)
print("\nReconstructed u:", reconstructed_u)
print("Original u:     ", u)
print("Are they equal?", np.allclose(reconstructed_u, u))

Orthonormal Basis:
|e1⟩ = [-0.33333333  0.66666667  0.66666667]
|e2⟩ = [ 0.66666667 -0.33333333  0.66666667]
|e3⟩ = [ 0.66666667  0.66666667 -0.33333333]

Coefficients:
c1 = 3.0
c2 = 6.0
c3 = -3.0

Reconstructed u: [ 1. -2.  7.]
Original u:      [ 1 -2  7]
Are they equal? True


## 1.6 Orthonormal Basis for a Two-Dimensional Subspace

Given the following vectors:

|v₁⟩ = (1, i, 1)ᵗ
|v₂⟩ = (3, 0, -3)ᵗ

Find an orthonormal basis for the two-dimensional subspace spanned by {|v₁⟩, |v₂⟩}.

Note: i represents the imaginary unit.

In [8]:
# Define the vectors
v1 = np.array([1, 1j, 1], dtype=complex)
v2 = np.array([3, 0, -3], dtype=complex)

vectors = [v1, v2]

# Apply Gram-Schmidt orthonormalization
orthonormal_basis = gram_schmidt(vectors)

print("Orthonormal Basis:")
for i, e in enumerate(orthonormal_basis, 1):
    print(f"|e{i}⟩ =", e)

# Verify orthonormality
print("\nVerifying orthonormality:")
for i, ei in enumerate(orthonormal_basis):
    for j, ej in enumerate(orthonormal_basis):
        inner_product = np.vdot(ei, ej)
        expected = 1 if i == j else 0
        print(f"⟨e{i+1}|e{j+1}⟩ = {inner_product:.4f} (Expected: {expected})")

# Verify that the basis spans the same subspace
print("\nVerifying span:")
for i, v in enumerate([v1, v2], 1):
    reconstructed = sum(np.vdot(v, e) * e for e in orthonormal_basis)
    print(f"|v{i}⟩ original:     ", v)
    print(f"|v{i}⟩ reconstructed:", reconstructed)
    print(f"Are they equal? {np.allclose(v, reconstructed)}\n")

Orthonormal Basis:
|e1⟩ = [0.57735027+0.j         0.        +0.57735027j 0.57735027+0.j        ]
|e2⟩ = [ 0.70710678+0.j  0.        +0.j -0.70710678+0.j]

Verifying orthonormality:
⟨e1|e1⟩ = 1.0000+0.0000j (Expected: 1)
⟨e1|e2⟩ = 0.0000+0.0000j (Expected: 0)
⟨e2|e1⟩ = 0.0000+0.0000j (Expected: 0)
⟨e2|e2⟩ = 1.0000+0.0000j (Expected: 1)

Verifying span:
|v1⟩ original:      [1.+0.j 0.+1.j 1.+0.j]
|v1⟩ reconstructed: [1.+0.j 0.+1.j 1.+0.j]
Are they equal? True

|v2⟩ original:      [ 3.+0.j  0.+0.j -3.+0.j]
|v2⟩ reconstructed: [ 3.+0.j  0.+0.j -3.+0.j]
Are they equal? True



## 1.8 Eigenvalue Problem

Let A be the following matrix:

A = [
    [1/√2,   0  ],
    [1+i,  1-i  ]
]

a) Find the eigenvalues and the corresponding normalized eigenvectors.

In [9]:

# Define the matrix A
A = np.array([
    [1/np.sqrt(2), 0],
    [1+1j, 1-1j]
], dtype=complex)

print("Matrix A:")
print(A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:")
for i, eigenvalue in enumerate(eigenvalues, 1):
    print(f"λ{i} = {eigenvalue}")

print("\nNormalized Eigenvectors:")
for i, eigenvector in enumerate(eigenvectors.T, 1):
    # Normalize the eigenvector
    normalized_eigenvector = eigenvector / np.linalg.norm(eigenvector)
    print(f"|v{i}⟩ = {normalized_eigenvector}")

# Verify the results
print("\nVerification:")
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T), 1):
    left_side = np.dot(A, eigenvector)
    right_side = eigenvalue * eigenvector
    print(f"For eigenpair {i}:")
    print(f"A|v{i}⟩ = {left_side}")
    print(f"λ{i}|v{i}⟩ = {right_side}")
    print(f"Are they equal? {np.allclose(left_side, right_side)}\n")

Matrix A:
[[0.70710678+0.j 0.        +0.j]
 [1.        +1.j 1.        -1.j]]

Eigenvalues:
λ1 = (1-1j)
λ2 = (0.7071067811865475+0j)

Normalized Eigenvectors:
|v1⟩ = [0.+0.j 1.+0.j]
|v2⟩ = [0.28463419+0.52043288j 0.80506707+0.j        ]

Verification:
For eigenpair 1:
A|v1⟩ = [0.+0.j 1.-1.j]
λ1|v1⟩ = [0.+0.j 1.-1.j]
Are they equal? True

For eigenpair 2:
A|v2⟩ = [0.20126677+0.36800162j 0.56926839+0.j        ]
λ2|v2⟩ = [0.20126677+0.36800162j 0.56926839+0.j        ]
Are they equal? True



b) Show that the eigenvectors are mutually orthogonal and that they satisfy the completeness
relation

In [10]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:")
for i, eigenvalue in enumerate(eigenvalues, 1):
    print(f"λ{i} = {eigenvalue}")

print("\nNormalized Eigenvectors:")
for i, eigenvector in enumerate(eigenvectors.T, 1):
    print(f"|v{i}⟩ = {eigenvector}")

# Check orthogonality
print("\nChecking orthogonality:")
for i, vi in enumerate(eigenvectors.T):
    for j, vj in enumerate(eigenvectors.T):
        inner_product = np.vdot(vi, vj)
        expected = 1 if i == j else 0
        print(f"⟨v{i+1}|v{j+1}⟩ = {inner_product:.4f} (Expected: {expected})")

# Check completeness relation
print("\nChecking completeness relation:")
completeness_sum = np.zeros((2, 2), dtype=complex)
for v in eigenvectors.T:
    outer_product = np.outer(v, np.conj(v))
    completeness_sum += outer_product

print("Sum of |v_i⟩⟨v_i|:")
print(completeness_sum)

identity = np.eye(2)
print("\nIdentity matrix:")
print(identity)

print(f"\nAre they equal? {np.allclose(completeness_sum, identity)}")


Eigenvalues:
λ1 = (1-1j)
λ2 = (0.7071067811865475+0j)

Normalized Eigenvectors:
|v1⟩ = [0.+0.j 1.+0.j]
|v2⟩ = [0.28463419+0.52043288j 0.80506707+0.j        ]

Checking orthogonality:
⟨v1|v1⟩ = 1.0000+0.0000j (Expected: 1)
⟨v1|v2⟩ = 0.8051+0.0000j (Expected: 0)
⟨v2|v1⟩ = 0.8051+0.0000j (Expected: 0)
⟨v2|v2⟩ = 1.0000+0.0000j (Expected: 1)

Checking completeness relation:
Sum of |v_i⟩⟨v_i|:
[[0.35186701+8.75660627e-18j 0.22914962+4.18983376e-01j]
 [0.22914962-4.18983376e-01j 1.64813299+0.00000000e+00j]]

Identity matrix:
[[1. 0.]
 [0. 1.]]

Are they equal? False


c) Find a unitary matrix which diagonalizes A.


In [11]:
# Define the matrix A
A = (1/np.sqrt(2)) * np.array([[0, 1 + 1j], [1 - 1j, 0]])

print("Original matrix A:")
print(A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# The matrix of eigenvectors is our unitary matrix
U = eigenvectors

print("\nUnitary matrix U that diagonalizes A:")
print(U)

# Verify that U is unitary
U_dag = np.conj(U.T)
I = np.eye(2)
print("\nVerifying U is unitary:")
print("U†U:")
print(np.matmul(U_dag, U))
print(f"Is U†U equal to the identity matrix? {np.allclose(np.matmul(U_dag, U), I)}")

# Diagonalize A
D = np.matmul(U_dag, np.matmul(A, U))

print("\nDiagonalized matrix D = U†AU:")
print(D)

# Verify diagonalization
A_reconstructed = np.matmul(U, np.matmul(D, U_dag))
print("\nReconstructed A = UDU†:")
print(A_reconstructed)
print(f"Is the reconstructed A equal to the original A? {np.allclose(A, A_reconstructed)}")

Original matrix A:
[[0.        +0.j         0.70710678+0.70710678j]
 [0.70710678-0.70710678j 0.        +0.j        ]]

Unitary matrix U that diagonalizes A:
[[ 0.5       +0.5j -0.5       -0.5j]
 [ 0.70710678+0.j   0.70710678+0.j ]]

Verifying U is unitary:
U†U:
[[1.00000000e+00+0.00000000e+00j 2.22044605e-16+2.77555756e-17j]
 [2.22044605e-16-2.77555756e-17j 1.00000000e+00+0.00000000e+00j]]
Is U†U equal to the identity matrix? True

Diagonalized matrix D = U†AU:
[[ 1.00000000e+00+0.00000000e+00j -1.11022302e-16-2.77555756e-17j]
 [-8.32667268e-17+2.77555756e-17j -1.00000000e+00+0.00000000e+00j]]

Reconstructed A = UDU†:
[[5.27355937e-16+0.00000000e+00j 7.07106781e-01+7.07106781e-01j]
 [7.07106781e-01-7.07106781e-01j 4.67705010e-16-1.18416987e-33j]]
Is the reconstructed A equal to the original A? True


1.9 b) ‡ Let U be unitary. Show that all the eigenvalues are unimodular (|λj | = 1).



In [12]:
import numpy as np

# Let's define a unitary matrix U (from a previous example)
A = (1/np.sqrt(2)) * np.array([[0, 1 + 1j], [1 - 1j, 0]])

# Compute the eigenvalues of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Check that all eigenvalues are unimodular (i.e., their magnitude is 1)
eigenvalue_magnitudes = np.abs(eigenvalues)

print("Eigenvalues:", eigenvalues)
print("Magnitudes of Eigenvalues:", eigenvalue_magnitudes)

# Check if all eigenvalue magnitudes are 1 (unimodular)
if np.allclose(eigenvalue_magnitudes, 1):
    print("All eigenvalues are unimodular (|λ| = 1).")
else:
    print("Some eigenvalues are not unimodular.")


Eigenvalues: [ 1.+5.55111512e-17j -1.-5.55111512e-17j]
Magnitudes of Eigenvalues: [1. 1.]
All eigenvalues are unimodular (|λ| = 1).



## 1.10 Eigenvalue Problem for a Special 3x3 Matrix

Let A be the following matrix:

A = [
    [0, 0, i],
    [0, i, 0],
    [i, 0, 0]
]

Where i is the imaginary unit.

Find the eigenvalues (without calculation if possible) and the corresponding eigenvectors.

In [13]:
import numpy as np

# Step 1: Define the eigenvalue and eigenvector matrices
lambda_1 = -1
lambda_2 = 3

# Eigenvector matrix P
P = np.array([[1/np.sqrt(2), 1/np.sqrt(2)],
              [-1j/np.sqrt(2), 1j/np.sqrt(2)]])
print ("Eigenvector matrix P: ", P)
# Step 2: Diagonal matrix D with eigenvalues
D = np.array([[lambda_1, 0], [0, lambda_2]])
print(f"Diagonal matrix D:  {D}")

# Step 3: Compute the conjugate transpose (P^-1) since P is unitary
P_inv = np.conj(P.T)
print("Conjugate transpose of P ", P_inv)
# Step 4: Compute the matrix A
A = np.dot(np.dot(P, D), P_inv)

# Step 5: Display the result
print("Matrix A:")
print(A)


Eigenvector matrix P:  [[ 0.70710678+0.j          0.70710678+0.j        ]
 [-0.        -0.70710678j  0.        +0.70710678j]]
Diagonal matrix D:  [[-1  0]
 [ 0  3]]
Conjugate transpose of P  [[ 0.70710678-0.j         -0.        +0.70710678j]
 [ 0.70710678-0.j          0.        -0.70710678j]]
Matrix A:
[[1.+0.j 0.-2.j]
 [0.+2.j 1.+0.j]]


## 1.13 Eigenvalue Problem for a 2x2 Matrix

Let A be the following matrix:

A = [
    [2, 1],
    [1, 2]
]

Find the eigenvalues and the corresponding normalized eigenvectors of A.

In [14]:
import numpy as np

# Define matrix A
A = np.array([[2, 1], [1, 2]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
# print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

# Normalize eigenvectors
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

# Print results
print("Eigenvalues:")
print(eigenvalues)
print("Normalized Eigenvectors:")
print(normalized_eigenvectors)



Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Eigenvalues:
[3. 1.]
Normalized Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]




*   Write down the spectral decomposition of A.






In [15]:
import numpy as np

# Define the matrix A
A = np.array([[2, 1], [1, 2]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Construct diagonal matrix Lambda
Lambda = np.diag(eigenvalues)

# Construct matrix V of eigenvectors
V = eigenvectors

# Compute V^-1 (which is the conjugate transpose for orthogonal eigenvectors)
V_inv = np.linalg.inv(V)

# Compute the spectral decomposition: A = V * Lambda * V_inv
A_reconstructed = np.dot(np.dot(V, Lambda), V_inv)

# Print results
print("Matrix A:")
print(A)
print("Eigenvalues (Lambda):")
print(Lambda)
print("Eigenvectors (V):")
print(V)
print("Reconstructed A (Spectral Decomposition):")
print(A_reconstructed)


Matrix A:
[[2 1]
 [1 2]]
Eigenvalues (Lambda):
[[3. 0.]
 [0. 1.]]
Eigenvectors (V):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Reconstructed A (Spectral Decomposition):
[[2. 1.]
 [1. 2.]]







*   Find exp(iA).




In [16]:
import numpy as np
from scipy.linalg import expm

# Define the matrix A
A = np.array([[2, 1], [1, 2]])

# Define the imaginary unit i
i = 1j

# Step 1: Compute the matrix exponential exp(iA)
exp_iA = expm(i * A)

# Print the result
print("exp(iA):")
print(exp_iA)




exp(iA):
[[-0.2248451+0.4912955j  -0.7651474-0.35017549j]
 [-0.7651474-0.35017549j -0.2248451+0.4912955j ]]


## 1.14 Eigenvalue Problem for a 3x3 Matrix

Let A be the following matrix:

A = [
    [ 5, -2, -4],
    [-2,  2,  2],
    [-4,  2,  5]
]

Find the eigenvalues and the corresponding eigenvectors of A.

In [23]:

# Define the matrix A
A = np.array([[5, -2, -4],
              [-2, 2, 2],
              [-4, 2, 5]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:")
for i, eigenvalue in enumerate(eigenvalues, 1):
    print(f"λ{i} = {eigenvalue:.4f}")

print("\nEigenvectors:")
for i, eigenvector in enumerate(eigenvectors.T, 1):
    print(f"v{i} = {eigenvector}")

# Verify that Av = λv for each eigenpair
print("\nVerifying Av = λv:")
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T), 1):
    Av = A @ eigenvector
    lambda_v = eigenvalue * eigenvector
    print(f"\nFor eigenpair {i}:")
    print(f"Av{i} = {Av}")
    print(f"λ{i}v{i} = {lambda_v}")
    print(f"Are they equal? {np.allclose(Av, lambda_v)}")

# Verify orthogonality of eigenvectors
print("\nVerifying orthogonality of eigenvectors:")
for i in range(3):
    for j in range(i+1, 3):
        dot_product = np.dot(eigenvectors[:, i], eigenvectors[:, j])
        print(f"v{i+1} · v{j+1} = {dot_product:.4e}")

# Reconstruct A using eigendecomposition
print("\nReconstructing A using eigendecomposition:")
A_reconstructed = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
print("Reconstructed A:")
print(A_reconstructed)
print(f"Is it equal to the original A? {np.allclose(A, A_reconstructed)}")



Eigenvalues:
λ1 = 10.0000+0.0000j
λ2 = 1.0000+0.0000j
λ3 = 1.0000-0.0000j

Eigenvectors:
v1 = [-0.66666667+0.j  0.33333333+0.j  0.66666667+0.j]
v2 = [-0.07408817+0.1093227j -0.90882435+0.j         0.380324  +0.1093227j]
v3 = [-0.07408817-0.1093227j -0.90882435-0.j         0.380324  -0.1093227j]

Verifying Av = λv:

For eigenpair 1:
Av1 = [-6.66666667+0.j  3.33333333+0.j  6.66666667+0.j]
λ1v1 = [-6.66666667+0.j  3.33333333+0.j  6.66666667+0.j]
Are they equal? True

For eigenpair 2:
Av2 = [-0.07408817+1.09322698e-01j -0.90882435+8.32667268e-17j
  0.380324  +1.09322698e-01j]
λ2v2 = [-0.07408817+1.09322698e-01j -0.90882435-1.65411012e-16j
  0.380324  +1.09322698e-01j]
Are they equal? True

For eigenpair 3:
Av3 = [-0.07408817-1.09322698e-01j -0.90882435-8.32667268e-17j
  0.380324  -1.09322698e-01j]
λ3v3 = [-0.07408817-1.09322698e-01j -0.90882435+1.65411012e-16j
  0.380324  -1.09322698e-01j]
Are they equal? True

Verifying orthogonality of eigenvectors:
v1 · v2 = 2.2204e-16+0.0000e+00j
v1 ·



*   Write down the spectral decomposition of A.





In [24]:

# Define the matrix A
A = np.array([[5, -2, -4],
              [-2, 2, 2],
              [-4, 2, 5]])

# Step 1: Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Step 2: Form the diagonal matrix of eigenvalues
Lambda = np.diag(eigenvalues)

# Step 3: Compute the inverse of the eigenvector matrix
V_inv = np.linalg.inv(eigenvectors)

# Step 4: Verify the spectral decomposition: A = V * Lambda * V_inv
A_reconstructed = np.dot(eigenvectors, np.dot(Lambda, V_inv))

# Print the results
print("Original Matrix A:")
print(A)

print("\nEigenvalues (Diagonal Matrix Lambda):")
print(Lambda)

print("\nEigenvectors (Matrix V):")
print(eigenvectors)

print("\nInverse of Eigenvector Matrix (V_inv):")
print(V_inv)

print("\nReconstructed Matrix A from Spectral Decomposition:")
print(A_reconstructed)


Original Matrix A:
[[ 5 -2 -4]
 [-2  2  2]
 [-4  2  5]]

Eigenvalues (Diagonal Matrix Lambda):
[[10.+0.00000000e+00j  0.+0.00000000e+00j  0.+0.00000000e+00j]
 [ 0.+0.00000000e+00j  1.+1.82005481e-16j  0.+0.00000000e+00j]
 [ 0.+0.00000000e+00j  0.+0.00000000e+00j  1.-1.82005481e-16j]]

Eigenvectors (Matrix V):
[[-0.66666667+0.j        -0.07408817+0.1093227j -0.07408817-0.1093227j]
 [ 0.33333333+0.j        -0.90882435+0.j        -0.90882435-0.j       ]
 [ 0.66666667+0.j         0.380324  +0.1093227j  0.380324  -0.1093227j]]

Inverse of Eigenvector Matrix (V_inv):
[[-0.66666667-0.j          0.33333333+0.j          0.66666667+0.j        ]
 [-0.12225807-2.45804309j -0.48903228-0.68494106j  0.12225807-2.11557255j]
 [-0.12225807+2.45804309j -0.48903228+0.68494106j  0.12225807+2.11557255j]]

Reconstructed Matrix A from Spectral Decomposition:
[[ 5.+9.75534922e-18j -2.+1.63438033e-18j -4.+9.09689550e-18j]
 [-2.+1.86196876e-17j  2.-3.75359993e-17j  2.-6.82478099e-17j]
 [-4.+2.34287721e-17j  2.+1




*  Find the inverse of A by making use of the spectral decomposition.



In [25]:
# print("Matrix A:")
# print(A)


# Spectral decomposition: A = VΛV^(-1)
# where V is the matrix of eigenvectors and Λ is the diagonal matrix of eigenvalues

# To find A^(-1), we use: A^(-1) = VΛ^(-1)V^(-1)
# where Λ^(-1) is a diagonal matrix with 1/λ_i on the diagonal

# Compute Λ^(-1)
lambda_inv = np.diag(1 / eigenvalues)

# Compute A^(-1)
A_inv = eigenvectors @ lambda_inv @ np.linalg.inv(eigenvectors)

print("\nInverse of A using spectral decomposition:")
print(A_inv)

# Verify the result
print("\nVerification:")
print("A * A^(-1):")
print(A @ A_inv)

print("\nA^(-1) * A:")
print(A_inv @ A)

# Compare with NumPy's built-in inverse function
A_inv_numpy = np.linalg.inv(A)
print("\nInverse of A using NumPy's inv function:")
print(A_inv_numpy)

print(f"\nAre the results equal? {np.allclose(A_inv, A_inv_numpy)}")

# Verify that A * A^(-1) = I
I = np.eye(3)
print(f"\nIs A * A^(-1) equal to the identity matrix? {np.allclose(A @ A_inv, I)}")
print(f"Is A^(-1) * A equal to the identity matrix? {np.allclose(A_inv @ A, I)}")



Inverse of A using spectral decomposition:
[[ 0.6+4.25421969e-18j  0.2-1.43303792e-18j  0.4+3.39475161e-18j]
 [ 0.2-4.25961841e-17j  0.9+3.24211377e-17j -0.2-5.34199477e-17j]
 [ 0.4+2.10083143e-17j -0.2-1.74710827e-17j  0.6-1.09547270e-17j]]

Verification:
A * A^(-1):
[[ 1.00000000e+00+2.24302094e-17j  1.11022302e-16-2.12313393e-18j
  -4.44089210e-16+1.67632561e-16j]
 [ 1.11022302e-15-5.16841789e-17j  1.00000000e+00+3.27661857e-17j
   1.11022302e-15-1.35538852e-16j]
 [ 4.99600361e-16+2.83232463e-18j -2.77555756e-17-1.67809867e-17j
   1.00000000e+00-1.75192537e-16j]]

A^(-1) * A:
[[ 1.00000000e+00+1.05581678e-17j  7.77156117e-16-4.58501198e-18j
   1.38777878e-15-2.90919652e-18j]
 [-2.22044605e-16-6.41434052e-17j  1.00000000e+00+4.31947482e-17j
   1.88737914e-15-3.18727266e-17j]
 [-8.88178420e-16+1.83802645e-16j  2.22044605e-16-9.88682481e-17j
   1.00000000e+00-1.73749058e-16j]]

Inverse of A using NumPy's inv function:
[[ 0.6  0.2  0.4]
 [ 0.2  0.9 -0.2]
 [ 0.4 -0.2  0.6]]

Are the res

## 1.16 Singular Value Decomposition (SVD)

Find the SVD of matrix A:

A = [
    [1, 0, i],
    [i, 0, 1]
]

Where i is the imaginary unit.

Note: The SVD of a matrix A is given by A = UΣV*, where:
- U is a unitary matrix
- Σ (Sigma) is a rectangular diagonal matrix with non-negative real numbers on the diagonal
- V* is the conjugate transpose of V, which is also a unitary matrix

In [26]:

# Define the matrix A
A = np.array([
    [1, 0, 1j],
    [1j, 0, 1]
], dtype=complex)

print("Matrix A:")
print(A)

# Compute the SVD
U, s, Vh = np.linalg.svd(A)

print("\nSingular Value Decomposition:")
print("U (left singular vectors):")
print(U)

print("\nΣ (singular values):")
print(s)

print("\nV* (conjugate transpose of right singular vectors):")
print(Vh)

# Construct the full Σ matrix
m, n = A.shape
Sigma = np.zeros((m, n))
Sigma[:m, :m] = np.diag(s)

print("\nFull Σ matrix:")
print(Sigma)

# Verify the decomposition
A_reconstructed = U @ Sigma @ Vh
print("\nReconstructed A:")
print(A_reconstructed)
print(f"Is the reconstruction accurate? {np.allclose(A, A_reconstructed)}")

# Verify properties of U and V
print("\nVerifying properties:")
print(f"Is U unitary? {np.allclose(U @ U.conj().T, np.eye(m))}")
print(f"Is V unitary? {np.allclose(Vh.conj().T @ Vh, np.eye(n))}")

# Compute and print the condition number
condition_number = np.linalg.cond(A)
print(f"\nCondition number of A: {condition_number}")

Matrix A:
[[1.+0.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 1.+0.j]]

Singular Value Decomposition:
U (left singular vectors):
[[-1.00000000e+00+0.00000000e+00j  2.35513869e-16+0.00000000e+00j]
 [ 0.00000000e+00+2.35513869e-16j  0.00000000e+00+1.00000000e+00j]]

Σ (singular values):
[1.41421356 1.41421356]

V* (conjugate transpose of right singular vectors):
[[-0.70710678+0.j          0.        +0.j          0.        -0.70710678j]
 [ 0.70710678+0.j          0.        +0.j          0.        -0.70710678j]
 [ 0.        +0.j         -1.        +0.j          0.        +0.j        ]]

Full Σ matrix:
[[1.41421356 0.         0.        ]
 [0.         1.41421356 0.        ]]

Reconstructed A:
[[1.+0.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 1.+0.j]]
Is the reconstruction accurate? True

Verifying properties:
Is U unitary? True
Is V unitary? True

Condition number of A: 1.0000000000000004
